### ISSUE TITLE
Question regarding injected classes prop

### ISSUE THREAD

**Issue by wKovacs64** [tizmagik/react-csjs#8]
I'm relatively new to React, so apologies if this is a dumb question. What is the purpose of injecting the `classes` prop into the target component and referencing class names from there as opposed to just using the original `styles` object that we already had?

Modified example from the README without using `classes`:

``` js
const styles = csjs`
  .button {
    background-color: purple
  }

  .label {
    color: blue
  }
`;

const Button = ({children}) => (
  <div className={styles.button}>
    <span className={styles.label}>
      {children}
    </span>
  </div>
);

export default withStyles(styles)(Button);
```

Is `classes` just provided to prevent `Button` from requiring that `styles` be in scope, or is there another benefit/use-case?

Logistically, using `classes` is somewhat awkward as popular lint rules and IDE analysis for React complain that it's missing from propTypes and, if added to the component's propTypes with `.isRequired` (which it would be?), that every reference to the element is missing the required attribute (unless you modify them all to include an empty placeholder `classes` attribute), etc.

Just trying to determine if it's worth the overhead. Thanks.

**Comment by tizmagik** [comment]
@wKovacs64 thanks for your question! This isn't a dumb question at all, you bring up a good point. With the way the library is currently written, yes, in most cases you _would_ have the `styles` object in scope and can forgo using the `classes` prop. 

You are actually free to do that today, and that way you wouldn't need to define it as a PropType, you can just ignore the `classes` prop altogether and eslint shouldn't complain.

However, I would be hesitant to remove the prop from the HoC entirely since we're actually looking into encompassing the `csjs` tagged template into `react-csjs` itself, see #9 -- when that gets merged then the only way to get at the classes defined would be via the `classes` property. And in that case, the best thing to do would probably be to just [suppress the eslint error for this specific prop](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#rule-options):

```
"prop-types": [2, { ignore: "classes" }]
```

Now that I think about it, this might be a good idea to add to the README anyway. Happy to accept a PR for this!

Thoughts?

**Comment by wKovacs64** [comment]
@tizmagik 

Yep, I've been watching this project closely and as soon as I saw the idea behind #9 mentioned on reddit, it dawned on me that `classes` would be necessary in that case. No reason to remove it, even if that doesn't get merged for some reason. I just wasn't sure if there was a good reason to use it that I wasn't seeing (outside of this new, mandatory use case).

Maybe I'll whip up a PR for the documentation.

Thanks! 👍
